server:
  port: 9991



gitee:
  owner: tyrell
  access_token: bdcfc5760d83a18041a83bc17fa02ede
  repo: tyrell
  local_path: /doc/gitee
  remote_path: https://tyrell.gitee.io

spring:
  datasource:
    url: jdbc:sqlite:/doc/myDB.db
    driver-class-name: org.sqlite.JDBC
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB